---
tiers:
    -
        name: onap
        order: 1
        ci_loop: '(daily)|(weekly)'
        description: >-
            Set of basic Functional tests to validate the ONAP installation.
        testcases:
            -
                case_name: robot_healthcheck
                project_name: functest
                criteria: 100
                blocking: true
                description: >-
                    This test case verifies the basic ONAP API: appc, sdnc,so,
                    vid, ....based on the default robot tests
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module: 'functest.core.robotframework'
                    class: 'RobotFramework'
                    args:
                        suites:
                            - /var/opt/OpenECOMP_ETE/robot/testsuites/robot_healthcheck.robot
                        pythonpath:
                            - /usr/local/lib/python-testing-utils/eteutils
                        variablefile:
                            - '/share/config/integration_robot_properties.py'
                            - '/share/config/integration_vm_properties.py'
                            - '/share/config/integration_preload_parameters.py'

            -
                case_name: robot_dcae
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies DCAE api
                    based on the default robot tests
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module: 'functest.core.robotframework'
                    class: 'RobotFramework'
                    args:
                        suites:
                            - /var/opt/OpenECOMP_ETE/robot/testsuites/robot_dcae.robot
                        pythonpath:
                            - /usr/local/lib/python-testing-utils/eteutils
                        variablefile:
                            - '/share/config/integration_robot_properties.py'
                            - '/share/config/integration_vm_properties.py'
                            - '/share/config/integration_preload_parameters.py'
            -
                case_name: robot_multicloud
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies the multicloud features of ONAP
                    based on the default robot tests
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module: 'functest.core.robotframework'
                    class: 'RobotFramework'
                    args:
                        suites:
                            - /var/opt/OpenECOMP_ETE/robot/testsuites/robot_multicloud.robot
                        pythonpath:
                            - /usr/local/lib/python-testing-utils/eteutils
                        variablefile:
                            - '/share/config/integration_robot_properties.py'
                            - '/share/config/integration_vm_properties.py'
                            - '/share/config/integration_preload_parameters.py'
            -
                case_name: robot_3rdparty
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies the ONAP 3rd party API
                    especially the different drivers
                    based on the default robot tests
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module: 'functest.core.robotframework'
                    class: 'RobotFramework'
                    args:
                        suites:
                            - /var/opt/OpenECOMP_ETE/robot/testsuites/robot_3rdparty.robot
                        pythonpath:
                            - /usr/local/lib/python-testing-utils/eteutils
                        variablefile:
                            - '/share/config/integration_robot_properties.py'
                            - '/share/config/integration_vm_properties.py'
                            - '/share/config/integration_preload_parameters.py'
